apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: true
  artifacts:
    - image: chachkie-fn
      buildpacks:
        builder: "gcr.io/buildpacks/builder:v1"
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
portForward:
  - resourceType: deployment
    resourceName: chachkie-fn
    port: 8080
    localPort: 3000