spring:
  cloud:
    stream:
      function:
        definition: names;chachkies;chachkiesSink
      bindings:
        names-out-0:
          binder: rabbit
          destination: chachkies
          content-type: text/plain
        chachkies-in-0:
          binder: rabbit
          destination: chachkies
          group: processor
        chachkies-out-0:
          binder: rabbit
          destination: named-chachkies
        chachkiesSink-in-0:
          binder: rabbit
          destination: named-chachkies
          group: sink
  rabbitmq:
    host: rabbitmq.default.svc.cluster.local
    port: 5672