apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-mgr
spec:
  ports:
  - port: 15672
    protocol: TCP
    nodePort: 31672
  type: NodePort
  selector:
    run: rabbitmq
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672
      protocol: TCP
      targetPort: 5672
  selector:
    run: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 5672
    - containerPort: 15672
  dnsPolicy: ClusterFirst
  restartPolicy: Never
